// Auto-generated by 단무지
window.companyActivitiesMeta = {
  "generatedAt": "2025-12-19 08:10:23",
  "matchPriority": [
    "bizNo",
    "certNo",
    "companyName"
  ],
  "totalActivities": 27,
  "matchedCompanies": 21,
  "unmatchedRows": 0,
  "ambiguousRows": 0,
  "excelFile": "가족회사 산학협력활동_251219.xlsx",
  "companyFile": "familyCompanies.js"
};

window.companyActivitiesByBizNo = {
  "1198689322": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "이재성 대표, 김동현 연구소장 참석(2인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 2
      }
    }
  ],
  "1228166806": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "이시영 실장(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 3
      }
    }
  ],
  "1318609672": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "이승수 대표(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 4
      }
    }
  ],
  "3128672094": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "최근욱 팀장(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 5
      }
    },
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "최근욱 팀장(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 28
      }
    }
  ],
  "3168703048": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "손원근 대표이사, 현봉수 CTO(2인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 6
      }
    },
    {
      "date": "2025-08-13",
      "type": "애로컨설팅",
      "title": "2025년 인천지역 기술 멘토링 사업",
      "result": "인천지방중소벤처기업사업 기술 멘토링 사업 결과보고",
      "dept": "산학협력팀",
      "owner": "김수민",
      "evidenceUrl": "인천지방중소벤처기업사업 기술 멘토링 사업 결과보고서 제출",
      "note": "전광길 교수(멘토)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 14
      }
    },
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "송원근 대표이사, 김혜진 이사(2인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 24
      }
    }
  ],
  "1228182903": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "이해광 수석(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 7
      }
    }
  ],
  "1318151063": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "임지영 팀장(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 8
      }
    },
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "임지영 팀장(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 26
      }
    }
  ],
  "1318609371": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "유길상 상무(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 9
      }
    }
  ],
  "2388801373": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "고부열 이사(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 10
      }
    }
  ],
  "1218127227": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "김보연 대리(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 11
      }
    },
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "김보연 대리(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 19
      }
    }
  ],
  "1228126347": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "오학성 CTO(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 12
      }
    },
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "오학성 CTO(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 25
      }
    }
  ],
  "6668601948": [
    {
      "date": "2025-10-17",
      "type": "간담회",
      "title": "제2차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonnews.com/news/articleView.html?idxno=430314",
      "note": "김우철 대표(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 13
      }
    }
  ],
  "5990800113": [
    {
      "date": "2025-08-13",
      "type": "애로컨설팅",
      "title": "2025년 인천지역 기술 멘토링 사업",
      "result": "인천지방중소벤처기업사업 기술 멘토링 사업 결과보고",
      "dept": "산학협력팀",
      "owner": "김수민",
      "evidenceUrl": "인천지방중소벤처기업사업 기술 멘토링 사업 결과보고서 제출",
      "note": "왕린 교수(멘토)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 15
      }
    }
  ],
  "1318632815": [
    {
      "date": "2025-08-13",
      "type": "애로컨설팅",
      "title": "2025년 인천지역 기술 멘토링 사업",
      "result": "인천지방중소벤처기업사업 기술 멘토링 사업 결과보고",
      "dept": "산학협력팀",
      "owner": "김수민",
      "evidenceUrl": "인천지방중소벤처기업사업 기술 멘토링 사업 결과보고서 제출",
      "note": "이민철 교수(멘토)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 16
      }
    }
  ],
  "1378186158": [
    {
      "date": "2025-08-13",
      "type": "애로컨설팅",
      "title": "2025년 인천지역 기술 멘토링 사업",
      "result": "인천지방중소벤처기업사업 기술 멘토링 사업 결과보고",
      "dept": "산학협력팀",
      "owner": "김수민",
      "evidenceUrl": "인천지방중소벤처기업사업 기술 멘토링 사업 결과보고서 제출",
      "note": "임원경 교수(멘토)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 17
      }
    }
  ],
  "3108125493": [
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "박진현 차장(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 18
      }
    }
  ],
  "1212523036": [
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "김은주 대표(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 20
      }
    }
  ],
  "2208113641": [
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "오정훈 수석매니저(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 21
      }
    }
  ],
  "1218604364": [
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "강수민 대표, 장두진 상무이사(2인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 22
      }
    }
  ],
  "1088121555": [
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "이정은 이사(1인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 23
      }
    }
  ],
  "1238131687": [
    {
      "date": "2025-07-11",
      "type": "간담회",
      "title": "제1차 유료 가족회사 간담회",
      "result": "유료 가족회사 간 상호 협력체계 마련",
      "dept": "산학협력팀",
      "owner": "서영주",
      "evidenceUrl": "https://www.incheonilbo.com/news/articleView.html?idxno=1295992",
      "note": "방근석 부장, 김정흠 부장(2인)",
      "source": {
        "matchMethod": "bizNo",
        "excelRow": 27
      }
    }
  ]
};

window.companyActivitiesUnmatched = [];

window.companyActivitiesAmbiguous = [];
